### ISSUE TITLE
Broken ext_typoscript_setup.txt

### ISSUE THREAD

**Issue by Schweriner** [SicorDev/sic_address#25] opened 2019-09-05 14:58 UTC
I'm having troubles with a broken ext_typoscript_setup.txt generated by the extension. After generating, the resulting files only contains:

```
SICOR\SicAddress\Domain\Model\Address {
                mapping {
                    tableName = tt_address
                }
            }
            updateReferenceIndex = 1
        }
    }
}
```

The first part is missing which of course results in a broken table mapping and exceptions. I think something goes wrong this the generation of this file through Fluid.

**Comment by SicorDev** [comment] 2019-09-06 05:57
Hi,

can you please check your template for ext_typoscript_setup.txt in .../ext/sic_address/Resources/Private/CodeTemplates/ext_typoscript_setup.txt and give us feedback again?

**Comment by Schweriner** [comment] 2019-09-06 08:02
The "source" file equals the original from the TER.

**Comment by Schweriner** [comment] 2019-09-06 10:23
Thats right.

**Comment by SicorDev** [comment] 2019-09-06 11:32
Did you compared your source file with the one on github?

Or tried to reinstall the extension? Maybe something went wrong on your last install from TER.

Do you use a fresh installation from TER or maybe updated a former customized version?

**Comment by Hobokens** [comment] 2019-09-07 08:40
Hi, 
I can confirm this issue.  I use sic_addess in combination with tt_address. I have 2 additional fields created by sic_address.  Yesterday I started an update from sic_address 2.1.0 to 2.1.1 using TER. After that I updated the generated model with the backend modul form sic_address because the search in FE diddn't work anymore. The result is the destroyed  ext_typoscript_setup.txt like Schweriner described it.

**Comment by SicorDev** [comment] 2019-09-09 05:41
Hi,

which version(s) of TYPO3, tt_address and sic_address do you use exactly?

We have downloaded the zip files for 2.1.1 and 2.1.0 from TER and compared them with the files of this git repository. There are no broken or missing files in the TER packages.

We still are not able to reproduce this issue. Can you both please remove your sic_address extension from your systems and install it again?

**Comment by SicorDev** [comment] 2019-09-10 07:55
Hi,

please tell us you PHP version, too.

**Comment by Hobokens** [comment] 2019-09-10 12:43
Hi, 
I'm using TYPO3 9.5.9, tt_address 5.0, sic_address 2.1.1.  and PHP 7.3.6.

After uninstalling and new installing sic_address I still have the described problems.

**Comment by SicorDev** [comment] 2019-09-18 13:36
Adnan, thnaks for the bugfix. After further inspecting the issue, I'm uncertain what to do, since it is basically a really awkward workaround for a fluid bug that has already been fixed:

https://github.com/TYPO3/Fluid/issues/453

I'm tempted to not release the workaround, but rather offer the suggestion to downgrade to PHP 7.2 until the TYPO3 source has been updated with a PHP 7.3 compatible fluid parser.

**Comment by SicorDev** [comment] 2019-09-30 11:03
This issue will not be fixed in sic_address. It has to be fixed in fluid.

Will will shrink our php dependencies to PHP 7.2 in our next release, until the fix is done in fluid.

**Comment by Hobokens** [comment] 2019-10-11 22:01
Thanks for investigating this issue.

**Comment by SicorDev** [comment] 2020-03-13 10:51
Support for PHP 7.3 and 7.4 has been activated in 2.4.1.

For more details read the CHANGELOG, please.

**Closed by SicorDev** 2020-03-13 10:51 UTC
